# Generated by Django 6.0.6 on 2026-07-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='category',
            new_name='category_name',
        ),
    ]
