# Generated by Django 6.0.6 on 2026-07-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_bannerdb_contactdb_registractiondb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registractiondb',
            old_name='Name',
            new_name='Username',
        ),
    ]
