# Generated by Django 6.0.6 on 2026-07-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_cartdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Price',
            new_name='price',
        ),
    ]
