# Generated by Django 6.0.6 on 2026-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_rename_price_cartdb_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistractionDB',
            new_name='RegisterDB',
        ),
    ]
