# Generated by Django 6.0.6 on 2026-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Client_Image', models.ImageField(blank=True, null=True, upload_to='client profiles')),
            ],
        ),
    ]
