# Generated by Django 6.0.6 on 2026-08-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_reviewdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerdb',
            name='Banner_Image',
        ),
        migrations.AddField(
            model_name='bannerdb',
            name='Banner_Video',
            field=models.FileField(blank=True, null=True, upload_to='Banner videos'),
        ),
    ]
